
package view;

import StudentNotAvailable.StudentNotAvailable;
import control.day_details;
import control.table_load;
import control.time_details;
import db.db_con;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import notavailable.NotAvailableTimes;
import process.delete_fun;
import process.fill_table;
import process.insert_time;
import timeallocation.TimeAllocations;

/**
 *
 * @author ACER
 */
public final class workingDays extends javax.swing.JFrame {

    public workingDays() {
        initComponents();
       
    }
    
    db_con con = new db_con();
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        txt_days = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hours_Combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        view = new javax.swing.JButton();
        min_combo = new javax.swing.JComboBox<>();
        Noday = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        combo_lec = new javax.swing.JComboBox<>();
        Noday1 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox10.setText("Saturday");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox11.setText("Sunday");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Time");

        txt_days.setEditable(false);
        txt_days.setBackground(new java.awt.Color(153, 153, 153));
        txt_days.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_days.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_days.setText("0");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Hours");

        hours_Combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hours_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        hours_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hours_ComboActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Minutes");

        submit.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 102, 0));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        view.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        view.setForeground(new java.awt.Color(102, 0, 102));
        view.setText("View Table");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        min_combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        min_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        min_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                min_comboActionPerformed(evt);
            }
        });

        Noday.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Noday.setText("No Of Working Days");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Select Woking Days");

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox1.setText("Monday");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox6.setText("Thuesday");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox7.setText("Wednesday");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox8.setText("Thusday");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox9.setText("Friday");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        combo_lec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        combo_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_lecActionPerformed(evt);
            }
        });

        Noday1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Noday1.setText("Lecturer Id");

        btn_delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 0, 0));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Noday1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Noday)
                                .addGap(18, 18, 18)
                                .addComponent(txt_days, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBox10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(207, 207, 207)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(184, 184, 184)
                                    .addComponent(combo_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(150, 150, 150)
                                    .addComponent(jLabel5)
                                    .addGap(34, 34, 34)
                                    .addComponent(hours_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(min_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(125, 125, 125))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Noday1)
                    .addComponent(combo_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Noday)
                    .addComponent(txt_days, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox11))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hours_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(min_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(view)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 640, 530));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 84, 720, 510));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Working Days And Hours");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 560, 60));

        jToggleButton1.setText("Add Location");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jToggleButton2.setText("Not Available Time For Students");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jToggleButton3.setText("Sessions and Not Available Times Allocations");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       
        int a = parseInt(txt_days.getText());
        if(jCheckBox1.isSelected()){
            a++;
            txt_days.setText(Integer.toString(a));
        }
        else{
            a--;
            txt_days.setText(Integer.toString(a));
        }
        

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        
    int a = parseInt(txt_days.getText());
            if(jCheckBox6.isSelected()){
                a++;
                txt_days.setText(Integer.toString(a));
            }
            else{
                a--;
                txt_days.setText(Integer.toString(a));
            }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
   
        int a = parseInt(txt_days.getText());
            if(jCheckBox7.isSelected()){
                a++;
                txt_days.setText(Integer.toString(a));
            }
            else{
                a--;
                txt_days.setText(Integer.toString(a));
            }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        
        int a = parseInt(txt_days.getText());
            if(jCheckBox8.isSelected()){
                a++;
                txt_days.setText(Integer.toString(a));
            }
            else{
                a--;
                txt_days.setText(Integer.toString(a));
            }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        
           int a = parseInt(txt_days.getText());
            if(jCheckBox9.isSelected()){
                a++;
                txt_days.setText(Integer.toString(a));
            }
            else{
                a--;
                txt_days.setText(Integer.toString(a));
            }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
       
           int a = parseInt(txt_days.getText());
            if(jCheckBox10.isSelected()){
                a++;
                txt_days.setText(Integer.toString(a));
            }
            else{
                a--;
                txt_days.setText(Integer.toString(a));
            }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
       
        int a = parseInt(txt_days.getText());
            if(jCheckBox11.isSelected()){
                a++;
                txt_days.setText(Integer.toString(a));
            }
            else{
                a--;
                txt_days.setText(Integer.toString(a));
            }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void hours_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hours_ComboActionPerformed
       
        System.out.println(hours_Combo.getSelectedItem());
    }//GEN-LAST:event_hours_ComboActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        /// variables
        int no_work;
        int hour;
        int min;
        
        int mon = 0;
        int tue = 0;
        int wed = 0;
        int thur = 0;
        int fri = 0;
        int sat = 0;
        int sun = 0;
        int l_id = 0;
        
                
        
        
        //value assign
        no_work = parseInt(txt_days.getText());
        hour = parseInt((String) hours_Combo.getSelectedItem());
        min = parseInt((String) min_combo.getSelectedItem());
        l_id = parseInt((String) combo_lec.getSelectedItem());
        
        if(jCheckBox11.isSelected()){
            sun = 1;
        }
        if(jCheckBox10.isSelected()){
            sat = 1;
        }
        if(jCheckBox9.isSelected()){
            fri = 1;
        }
        if(jCheckBox8.isSelected()){
            thur = 1;
        }
        if(jCheckBox7.isSelected()){
            wed = 1;
        }
        if(jCheckBox6.isSelected()){
            tue = 1;
        }
        if(jCheckBox1.isSelected()){
            mon = 1;
        }
        
        time_details td = new time_details();
        insert_time it = new insert_time();
        day_details dd = new day_details();
        
        td.setTime_min(min);
        td.setTime_hour(hour);
        td.setNo_date(no_work);
        td.setL_id(l_id);
        
        dd.setFri(fri);
        dd.setL_id(l_id);
        dd.setMon(mon);
        dd.setSat(sat);
        dd.setSun(sun);
        dd.setTue(tue);
        dd.setThur(thur);
        dd.setWed(wed);
        
        int output = 0;
        try {
            output = it.insert_table(td,dd);
            if(output == 1){
                JOptionPane.showMessageDialog(this, "Success!!! Data inseted");
            }
            
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error!!! This lecturer details are already added"+"\n*"+ex+"*");
        }


    }//GEN-LAST:event_submitActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
       
        jTable1.setModel(new DefaultTableModel(null,new String[]{"Time","Monday","Tuesday","Wdnesday","Thursday","Friday","Saturday","Sunday"}));
        int l_id = parseInt((String) combo_lec.getSelectedItem());
        day_details dd = new day_details();
        dd.setL_id(l_id);
        
        
        fill_table tl = new fill_table();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<fill_table.User> list = tl.ListUsers(dd);
        Object rowData[] = new Object[8];
        int size = list.size();
        System.out.println(size);
        if(size > 0){
            for(int i = 0; i < list.size(); i++)
            {
                rowData[0] = list.get(i).time;
                rowData[1] = list.get(i).mon;
                rowData[2] = list.get(i).tue;
                rowData[3] = list.get(i).wed;
                rowData[4] = list.get(i).thur;
                rowData[5] = list.get(i).fri;
                rowData[6] = list.get(i).sat;
                rowData[7] = list.get(i).sun;
                model.addRow(rowData);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "No Data!!!");
        }
        

        //dispose();

    }//GEN-LAST:event_viewActionPerformed

    private void min_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_min_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_min_comboActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int l_id = parseInt((String) combo_lec.getSelectedItem());
        
        day_details dd = new day_details();
        delete_fun df = new delete_fun();
        
        dd.setL_id(l_id);
        try {
            int output = df.delet_table(dd);
            JOptionPane.showMessageDialog(this, "Success!!! Data deleted");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error!!! This lecturer details cannot delete "+"\n*"+ex+"*");
        }
        
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void combo_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_lecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_lecActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        
         StudentNotAvailable table = new StudentNotAvailable();
         table.setVisible(true);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        
         NotAvailableTimes table = new NotAvailableTimes();
         table.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        
         TimeAllocations table = new TimeAllocations();
         table.setVisible(true);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workingDays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workingDays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Noday;
    private javax.swing.JLabel Noday1;
    private javax.swing.JButton btn_delete;
    private javax.swing.JComboBox<String> combo_lec;
    private javax.swing.JComboBox<String> hours_Combo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JComboBox<String> min_combo;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txt_days;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
